<?php

namespace AppBundle\Repository;

/**
 * ArduinoDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArduinoDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
